Wrong jar dependencies caused a java.lang.NoClassDefFoundError: Could not initialize class net.sf.cglib.proxy.Enhancer
git-svn-id: https://iritgo-aktera.googlecode.com/svn/trunk@102 71e8ea69-9a4e-8955-45a5-bfab6559e1dc